### ISSUE TITLE
Exception on single player game with "all kind" of tracks

### ISSUE THREAD

**Issue by flying-aces-hb** [PhilippvK/playforia-minigolf#55]
Hello,

After starting a single player game and selecting "all kinds" of tracks, I get the following exception on the server (client just hangs waiting):

```
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at org.moparforia.server.track.TrackManager.getRandomTracks(TrackManager.java:183)
        at org.moparforia.server.game.gametypes.golf.TrainingGame.initTracks(TrainingGame.java:35)
        at org.moparforia.server.game.gametypes.GolfGame.<init>(GolfGame.java:65)
        at org.moparforia.server.game.gametypes.golf.TrainingGame.<init>(TrainingGame.java:19)
        at org.moparforia.server.net.packethandlers.golf.LobbyCreateSinglePlayerHandler.handle(LobbyCreateSinglePlayerHandler.java:36)
        at org.moparforia.server.event.PacketReceivedEvent.processMessage(PacketReceivedEvent.java:34)
        at org.moparforia.server.event.PacketReceivedEvent.process(PacketReceivedEvent.java:20)
        at org.moparforia.server.Server.run(Server.java:197)
        at java.lang.Thread.run(Thread.java:748)
```

Using OpenJDK 1.8 on Arch Linux.

Looks like the track collection is not properly initialized when selecting all kinds of tracks?

**Comment by PhilippvK** [comment]
As I removed all `custom` tracks (see #24deaf86c48db37deccd80a4e3265cd7b79a4a0d) the category is empty which results in this error when the `All` category is chosen.

If I remember correctly i once fixed this on the server side but forgot to push the changes to the client code. If I can find the missing commits, it should be easy to resolve!

I will have a look into it later!

**Comment by PhilippvK** [comment]
I prepared a patch here: acf4d111423f7b4b5725b62b345a5c0a76ebc731

It can not be applied directly because auf the new project structure but I should be able to apply it to the master branch soon.

Do you compile the client/server by yourself or do you need the precompiled binaries to be updated as well?

**Comment by flying-aces-hb** [comment]
Thanks! There's no hurry, if need be I can compile it myself, but right now I'm just hosting a server for some people and stumbled on this bug when I started up a test game, so I thought I'd leave a comment about it here. I'll close this then, thanks for the quick response.

**Comment by PhilippvK** [comment]
@flying-aces-hb There you go: #56 

It would be great if you could try it out any time and let me know it it works like expected!
